language: python
python:
- '2.7'
install: pip install -r requirements.txt
script: ( sleep 10s && python stop.py ) & python launcher.py; echo "Server stopped"
deploy:
  provider: heroku
  app: buddycloud-inspection
  api_key:
    secure: 0nEhIZFxZls+vWkYYkUfkEW0OsAEas5mCWTJONeB4A4DiqwVRlvF7TktNk6aMIczsL6X2Buf71WODMPpFajZfW0Oovzf9B+n+i155C6vGTEoMRKI+4S+/2HbN0hyc5c12UfXhU0eDXx154OtEkWrT1+0nQvZym4SEKXUYTXDpxc=
